name: AiTown
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
# include:     ['.htaccess']
exclude:     []
keep_files:  ['.git','.svn']
timezone:    nil
future:      true
show_drafts: nil
limit_posts: 0
pygments:    true
relative_permalinks: true
permalink:     date
paginate_path: 'page:num'
port: 4001
baseurl: 'http://tnick.github.io/aitown'

