/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "aitown_messages.pb-c.h"
void   ai_town_index_add__init
                     (AiTownIndexAdd         *message)
{
  static AiTownIndexAdd init_value = AI_TOWN_INDEX_ADD__INIT;
  *message = init_value;
}
size_t ai_town_index_add__get_packed_size
                     (const AiTownIndexAdd *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ai_town_index_add__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ai_town_index_add__pack
                     (const AiTownIndexAdd *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ai_town_index_add__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ai_town_index_add__pack_to_buffer
                     (const AiTownIndexAdd *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ai_town_index_add__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AiTownIndexAdd *
       ai_town_index_add__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AiTownIndexAdd *)
     protobuf_c_message_unpack (&ai_town_index_add__descriptor,
                                allocator, len, data);
}
void   ai_town_index_add__free_unpacked
                     (AiTownIndexAdd *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ai_town_index_add__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ai_town_index_rem__init
                     (AiTownIndexRem         *message)
{
  static AiTownIndexRem init_value = AI_TOWN_INDEX_REM__INIT;
  *message = init_value;
}
size_t ai_town_index_rem__get_packed_size
                     (const AiTownIndexRem *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ai_town_index_rem__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ai_town_index_rem__pack
                     (const AiTownIndexRem *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ai_town_index_rem__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ai_town_index_rem__pack_to_buffer
                     (const AiTownIndexRem *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ai_town_index_rem__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AiTownIndexRem *
       ai_town_index_rem__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AiTownIndexRem *)
     protobuf_c_message_unpack (&ai_town_index_rem__descriptor,
                                allocator, len, data);
}
void   ai_town_index_rem__free_unpacked
                     (AiTownIndexRem *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ai_town_index_rem__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ai_town_index__init
                     (AiTownIndex         *message)
{
  static AiTownIndex init_value = AI_TOWN_INDEX__INIT;
  *message = init_value;
}
size_t ai_town_index__get_packed_size
                     (const AiTownIndex *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ai_town_index__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ai_town_index__pack
                     (const AiTownIndex *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ai_town_index__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ai_town_index__pack_to_buffer
                     (const AiTownIndex *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ai_town_index__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AiTownIndex *
       ai_town_index__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AiTownIndex *)
     protobuf_c_message_unpack (&ai_town_index__descriptor,
                                allocator, len, data);
}
void   ai_town_index__free_unpacked
                     (AiTownIndex *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ai_town_index__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ai_town_index_reply__init
                     (AiTownIndexReply         *message)
{
  static AiTownIndexReply init_value = AI_TOWN_INDEX_REPLY__INIT;
  *message = init_value;
}
size_t ai_town_index_reply__get_packed_size
                     (const AiTownIndexReply *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ai_town_index_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ai_town_index_reply__pack
                     (const AiTownIndexReply *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ai_town_index_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ai_town_index_reply__pack_to_buffer
                     (const AiTownIndexReply *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ai_town_index_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AiTownIndexReply *
       ai_town_index_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AiTownIndexReply *)
     protobuf_c_message_unpack (&ai_town_index_reply__descriptor,
                                allocator, len, data);
}
void   ai_town_index_reply__free_unpacked
                     (AiTownIndexReply *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ai_town_index_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ai_town_index_add__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(AiTownIndexAdd, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(AiTownIndexAdd, address),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(AiTownIndexAdd, has_port),
    PROTOBUF_C_OFFSETOF(AiTownIndexAdd, port),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ai_town_index_add__field_indices_by_name[] = {
  1,   /* field[1] = address */
  0,   /* field[0] = name */
  2,   /* field[2] = port */
};
static const ProtobufCIntRange ai_town_index_add__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ai_town_index_add__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ai_town_index_add",
  "AiTownIndexAdd",
  "AiTownIndexAdd",
  "",
  sizeof(AiTownIndexAdd),
  3,
  ai_town_index_add__field_descriptors,
  ai_town_index_add__field_indices_by_name,
  1,  ai_town_index_add__number_ranges,
  (ProtobufCMessageInit) ai_town_index_add__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ai_town_index_rem__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(AiTownIndexRem, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ai_town_index_rem__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange ai_town_index_rem__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ai_town_index_rem__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ai_town_index_rem",
  "AiTownIndexRem",
  "AiTownIndexRem",
  "",
  sizeof(AiTownIndexRem),
  1,
  ai_town_index_rem__field_descriptors,
  ai_town_index_rem__field_indices_by_name,
  1,  ai_town_index_rem__number_ranges,
  (ProtobufCMessageInit) ai_town_index_rem__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ai_town_index__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(AiTownIndex, type),
    &ai_town_index_message_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(AiTownIndex, version),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "add",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(AiTownIndex, add),
    &ai_town_index_add__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rem",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(AiTownIndex, rem),
    &ai_town_index_rem__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ai_town_index__field_indices_by_name[] = {
  2,   /* field[2] = add */
  3,   /* field[3] = rem */
  0,   /* field[0] = type */
  1,   /* field[1] = version */
};
static const ProtobufCIntRange ai_town_index__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ai_town_index__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ai_town_index",
  "AiTownIndex",
  "AiTownIndex",
  "",
  sizeof(AiTownIndex),
  4,
  ai_town_index__field_descriptors,
  ai_town_index__field_indices_by_name,
  1,  ai_town_index__number_ranges,
  (ProtobufCMessageInit) ai_town_index__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ai_town_index_reply__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(AiTownIndexReply, type),
    &ai_town_index_message_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(AiTownIndexReply, version),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_message",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(AiTownIndexReply, error_message),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "list",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(AiTownIndexReply, n_list),
    PROTOBUF_C_OFFSETOF(AiTownIndexReply, list),
    &ai_town_index_add__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ai_town_index_reply__field_indices_by_name[] = {
  2,   /* field[2] = error_message */
  3,   /* field[3] = list */
  0,   /* field[0] = type */
  1,   /* field[1] = version */
};
static const ProtobufCIntRange ai_town_index_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ai_town_index_reply__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ai_town_index_reply",
  "AiTownIndexReply",
  "AiTownIndexReply",
  "",
  sizeof(AiTownIndexReply),
  4,
  ai_town_index_reply__field_descriptors,
  ai_town_index_reply__field_indices_by_name,
  1,  ai_town_index_reply__number_ranges,
  (ProtobufCMessageInit) ai_town_index_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue ai_town_index_message_type__enum_values_by_number[5] =
{
  { "AITMT_INDEX_OK", "AI_TOWN_INDEX_MESSAGE_TYPE__AITMT_INDEX_OK", 0 },
  { "AITMT_INDEX_ERROR", "AI_TOWN_INDEX_MESSAGE_TYPE__AITMT_INDEX_ERROR", 1 },
  { "AITMT_INDEX_ADD", "AI_TOWN_INDEX_MESSAGE_TYPE__AITMT_INDEX_ADD", 2 },
  { "AITMT_INDEX_REM", "AI_TOWN_INDEX_MESSAGE_TYPE__AITMT_INDEX_REM", 3 },
  { "AITMT_INDEX_LIST", "AI_TOWN_INDEX_MESSAGE_TYPE__AITMT_INDEX_LIST", 4 },
};
static const ProtobufCIntRange ai_town_index_message_type__value_ranges[] = {
{0, 0},{0, 5}
};
const ProtobufCEnumValueIndex ai_town_index_message_type__enum_values_by_name[5] =
{
  { "AITMT_INDEX_ADD", 2 },
  { "AITMT_INDEX_ERROR", 1 },
  { "AITMT_INDEX_LIST", 4 },
  { "AITMT_INDEX_OK", 0 },
  { "AITMT_INDEX_REM", 3 },
};
const ProtobufCEnumDescriptor ai_town_index_message_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "ai_town_index_message_type",
  "ai_town_index_message_type",
  "AiTownIndexMessageType",
  "",
  5,
  ai_town_index_message_type__enum_values_by_number,
  5,
  ai_town_index_message_type__enum_values_by_name,
  1,
  ai_town_index_message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
