#include "config-builder.h"

#include <aitown/error_codes.h>
#include <aitown/dbg_assert.h>
#include <aitown/cfgpath.h>
#include <aitown/dir_utils.h>
#include <aitown/config.h>


#include <stdio.h>


#define KYOTO_NAME  "buildin-kyoto"
#define TOKYO_NAME  "buildin-tokyo"
#define MYSQL_NAME  "buildin-mysql"

#define IF_FLAG_IS_SET(__f__)   if ((flags & __f__) == __f__)

const char * write_config_file(const char * name, int flags) {

    // het full file path
    int sz_p = strlen (OS_TEMPORARY_DIR);
    int sz_f = strlen (name) + 32;
    char * ret = (char*)malloc (sz_p+sz_f);
    DBG_ASSERT (ret != NULL);

    sprintf (ret, "%s/%s.ini", OS_TEMPORARY_DIR, name);

    FILE * f = fopen (ret, "w");
    DBG_ASSERT (f != NULL);


    fprintf (f,
             ";\n"
             "; test config file generated by write_config_file()\n"
             "; function in tests/config-builder.c\n"
             ";\n"
             "\n");


    IF_FLAG_IS_SET(CFGTEST_DRIVERS) {
        fprintf (f,
                 "[drivers]\n"
                 "\n");
    }

    IF_FLAG_IS_SET(CFGTEST_DRIVERS_KYOTO) {
        fprintf (f,
                 "[drivers/" KYOTO_NAME "]\n"
                 "\n");
    }

    IF_FLAG_IS_SET(CFGTEST_DRIVERS_TOKYO) {
        fprintf (f,
                 "[drivers/" TOKYO_NAME "]\n"
                 "\n");
    }

    IF_FLAG_IS_SET(CFGTEST_DRIVERS_MYSQL) {
        fprintf (f,
                 "[drivers/" MYSQL_NAME "]\n"
                 "\n");
    }

    IF_FLAG_IS_SET(CFGTEST_DATABASES) {
        fprintf (f,
                 "[databases]\n"
                 "\n");
    }

    IF_FLAG_IS_SET(CFGTEST_DATABASES) {
        fprintf (f,
                 "[databases/iddatabase]\n"
                 "  \n"
                 "  driver = " KYOTO_NAME "\n"
                 "  path_hint = %s\n"
                 "  key_len = 8\n"
                 "  value_len = \n"
                 "\n"
                 "[dstorage]\n"
                 "  id_database = \"iddatabase\"\n"
                 "\n"
                 , OS_TEMPORARY_DIR);
    }

    IF_FLAG_IS_SET(CFGTEST_DSTORAGE) {
        fprintf (f,
                 "[dstorage]\n"
                 "\n");
    }

    IF_FLAG_IS_SET(CFGTEST_DSTORAGE_CTRL) {
        fprintf (f,
                 "[dstorage/controllers]\n"
                 "\n");
    }

    IF_FLAG_IS_SET(CFGTEST_DSTORAGE_CTRL_1) {
        fprintf (f,
                 "[databases/ctrl1]\n"
                 "  \n"
                 "  driver = " KYOTO_NAME "\n"
                 "  path_hint = %s\n"
                 "  key_len = 8\n"
                 "  value_len = \n"
                 "\n"
                 "[dstorage/controllers/0]\n"
                 "  database = \"ctrl1\"\n"
                 "\n", OS_TEMPORARY_DIR);
    }


    fclose (f);

    return ret;
}
